scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha010_gamma0750/results/evaluation.csv experiments/param_sweep/stage2/alpha010_gamma0750/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha010_gamma0775/results/evaluation.csv experiments/param_sweep/stage2/alpha010_gamma0775/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha010_gamma0800/results/evaluation.csv experiments/param_sweep/stage2/alpha010_gamma0800/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha010_gamma0825/results/evaluation.csv experiments/param_sweep/stage2/alpha010_gamma0825/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha010_gamma0850/results/evaluation.csv experiments/param_sweep/stage2/alpha010_gamma0850/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha015_gamma0750/results/evaluation.csv experiments/param_sweep/stage2/alpha015_gamma0750/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha015_gamma0775/results/evaluation.csv experiments/param_sweep/stage2/alpha015_gamma0775/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha015_gamma0800/results/evaluation.csv experiments/param_sweep/stage2/alpha015_gamma0800/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha015_gamma0825/results/evaluation.csv experiments/param_sweep/stage2/alpha015_gamma0825/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha015_gamma0850/results/evaluation.csv experiments/param_sweep/stage2/alpha015_gamma0850/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha020_gamma0750/results/evaluation.csv experiments/param_sweep/stage2/alpha020_gamma0750/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha020_gamma0775/results/evaluation.csv experiments/param_sweep/stage2/alpha020_gamma0775/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha020_gamma0800/results/evaluation.csv experiments/param_sweep/stage2/alpha020_gamma0800/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha020_gamma0825/results/evaluation.csv experiments/param_sweep/stage2/alpha020_gamma0825/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha020_gamma0850/results/evaluation.csv experiments/param_sweep/stage2/alpha020_gamma0850/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha025_gamma0750/results/evaluation.csv experiments/param_sweep/stage2/alpha025_gamma0750/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha025_gamma0775/results/evaluation.csv experiments/param_sweep/stage2/alpha025_gamma0775/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha025_gamma0800/results/evaluation.csv experiments/param_sweep/stage2/alpha025_gamma0800/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha025_gamma0825/results/evaluation.csv experiments/param_sweep/stage2/alpha025_gamma0825/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha025_gamma0850/results/evaluation.csv experiments/param_sweep/stage2/alpha025_gamma0850/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha030_gamma0750/results/evaluation.csv experiments/param_sweep/stage2/alpha030_gamma0750/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha030_gamma0775/results/evaluation.csv experiments/param_sweep/stage2/alpha030_gamma0775/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha030_gamma0800/results/evaluation.csv experiments/param_sweep/stage2/alpha030_gamma0800/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha030_gamma0825/results/evaluation.csv experiments/param_sweep/stage2/alpha030_gamma0825/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/stage2/alpha030_gamma0850/results/evaluation.csv experiments/param_sweep/stage2/alpha030_gamma0850/results/

