scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha040_gamma81/results/evaluation.csv experiments/param_sweep/round2/alpha040_gamma81/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha040_gamma83/results/evaluation.csv experiments/param_sweep/round2/alpha040_gamma83/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha040_gamma85/results/evaluation.csv experiments/param_sweep/round2/alpha040_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha040_gamma87/results/evaluation.csv experiments/param_sweep/round2/alpha040_gamma87/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha040_gamma89/results/evaluation.csv experiments/param_sweep/round2/alpha040_gamma89/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha045_gamma81/results/evaluation.csv experiments/param_sweep/round2/alpha045_gamma81/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha045_gamma83/results/evaluation.csv experiments/param_sweep/round2/alpha045_gamma83/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha045_gamma85/results/evaluation.csv experiments/param_sweep/round2/alpha045_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha045_gamma87/results/evaluation.csv experiments/param_sweep/round2/alpha045_gamma87/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha045_gamma89/results/evaluation.csv experiments/param_sweep/round2/alpha045_gamma89/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha050_gamma81/results/evaluation.csv experiments/param_sweep/round2/alpha050_gamma81/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha050_gamma83/results/evaluation.csv experiments/param_sweep/round2/alpha050_gamma83/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha050_gamma85/results/evaluation.csv experiments/param_sweep/round2/alpha050_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha050_gamma87/results/evaluation.csv experiments/param_sweep/round2/alpha050_gamma87/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha050_gamma89/results/evaluation.csv experiments/param_sweep/round2/alpha050_gamma89/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha055_gamma81/results/evaluation.csv experiments/param_sweep/round2/alpha055_gamma81/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha055_gamma83/results/evaluation.csv experiments/param_sweep/round2/alpha055_gamma83/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha055_gamma85/results/evaluation.csv experiments/param_sweep/round2/alpha055_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha055_gamma87/results/evaluation.csv experiments/param_sweep/round2/alpha055_gamma87/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha055_gamma89/results/evaluation.csv experiments/param_sweep/round2/alpha055_gamma89/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha060_gamma81/results/evaluation.csv experiments/param_sweep/round2/alpha060_gamma81/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha060_gamma83/results/evaluation.csv experiments/param_sweep/round2/alpha060_gamma83/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha060_gamma85/results/evaluation.csv experiments/param_sweep/round2/alpha060_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha060_gamma87/results/evaluation.csv experiments/param_sweep/round2/alpha060_gamma87/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round2/alpha060_gamma89/results/evaluation.csv experiments/param_sweep/round2/alpha060_gamma89/results/
