scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha01_gamma75/results/evaluation.csv experiments/param_sweep/round1/alpha01_gamma75/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha01_gamma80/results/evaluation.csv experiments/param_sweep/round1/alpha01_gamma80/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha01_gamma85/results/evaluation.csv experiments/param_sweep/round1/alpha01_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha01_gamma90/results/evaluation.csv experiments/param_sweep/round1/alpha01_gamma90/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha01_gamma95/results/evaluation.csv experiments/param_sweep/round1/alpha01_gamma95/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha03_gamma75/results/evaluation.csv experiments/param_sweep/round1/alpha03_gamma75/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha03_gamma80/results/evaluation.csv experiments/param_sweep/round1/alpha03_gamma80/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha03_gamma85/results/evaluation.csv experiments/param_sweep/round1/alpha03_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha03_gamma90/results/evaluation.csv experiments/param_sweep/round1/alpha03_gamma90/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha03_gamma95/results/evaluation.csv experiments/param_sweep/round1/alpha03_gamma95/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha05_gamma75/results/evaluation.csv experiments/param_sweep/round1/alpha05_gamma75/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha05_gamma80/results/evaluation.csv experiments/param_sweep/round1/alpha05_gamma80/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha05_gamma85/results/evaluation.csv experiments/param_sweep/round1/alpha05_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha05_gamma90/results/evaluation.csv experiments/param_sweep/round1/alpha05_gamma90/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha05_gamma95/results/evaluation.csv experiments/param_sweep/round1/alpha05_gamma95/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha07_gamma75/results/evaluation.csv experiments/param_sweep/round1/alpha07_gamma75/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha07_gamma80/results/evaluation.csv experiments/param_sweep/round1/alpha07_gamma80/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha07_gamma85/results/evaluation.csv experiments/param_sweep/round1/alpha07_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha07_gamma90/results/evaluation.csv experiments/param_sweep/round1/alpha07_gamma90/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha07_gamma95/results/evaluation.csv experiments/param_sweep/round1/alpha07_gamma95/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha09_gamma75/results/evaluation.csv experiments/param_sweep/round1/alpha09_gamma75/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha09_gamma80/results/evaluation.csv experiments/param_sweep/round1/alpha09_gamma80/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha09_gamma85/results/evaluation.csv experiments/param_sweep/round1/alpha09_gamma85/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha09_gamma90/results/evaluation.csv experiments/param_sweep/round1/alpha09_gamma90/results/
scp geraint@harpy.maths.cf.ac.uk:bed_moves_policy/src/experiments/param_sweep/round1/alpha09_gamma95/results/evaluation.csv experiments/param_sweep/round1/alpha09_gamma95/results/
